'use strict';
V.settings=()=>`<div class="set"><section class="panel"><header><h3>Workspace</h3></header><div class="pad"><label>Your name<input id="sn" value="${esc(S.settings.name)}" maxlength="20" oninput="this.value=this.value.slice(0,20)"></label>
<fieldset class="currency-picker"><legend>Currency</legend><div class="currency-options">${[['₹','INR'],['<div class="acts"><button class="btn" onclick="ssave()">Save settings</button></div></div></section>
<section class="panel"><header><h3>YouTube</h3></header><div class="pad"><p>Not connected. Channel sync arrives once Firebase and the YouTube API are set up.</p><div class="acts"><button class="btn ghost" onclick="toast('YouTube sign-in needs Firebase configured first.')">Connect channel</button></div></div></section>
<section class="panel"><header><h3>Your data</h3></header><div class="pad"><p>Everything is stored in this browser until a backend is connected.</p><div class="acts"><button class="btn ghost" onclick="sexp()">Export backup</button><button class="btn del" onclick="srst()">Reset workspace</button></div></div></section></div>`;
function scurrency(symbol){$('#sc').value=symbol;document.querySelectorAll('.currency-choice').forEach(b=>{const on=b.dataset.currency===symbol;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))})}
function ssave(){S.settings.name=$('#sn').value.trim().slice(0,20)||'Creator';S.settings.cur=$('#sc').value;save();toast('Settings saved')}
function sexp(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='vyro-backup.json';a.click();URL.revokeObjectURL(a.href)}
function srst(){if(confirm('Erase all videos, tasks, deals and events on this device?')){S=seed();save();go('home');toast('Workspace reset')}}
,'USD'],['€','EUR'],['£','GBP']].map(([symbol,code])=>`<button type="button" class="currency-choice ${(S.settings.cur||'₹')===symbol?'selected':''}" data-currency="${symbol}" aria-pressed="${(S.settings.cur||'₹')===symbol}" onclick="scurrency('${symbol}')"><strong>${symbol}</strong><span>${code}</span></button>`).join('')}</div><input type="hidden" id="sc" value="${S.settings.cur||'₹'}"></fieldset><div class="acts"><button class="btn" onclick="ssave()">Save settings</button></div></div></section>
<section class="panel"><header><h3>YouTube</h3></header><div class="pad"><p>Not connected. Channel sync arrives once Firebase and the YouTube API are set up.</p><div class="acts"><button class="btn ghost" onclick="toast('YouTube sign-in needs Firebase configured first.')">Connect channel</button></div></div></section>
<section class="panel"><header><h3>Your data</h3></header><div class="pad"><p>Everything is stored in this browser until a backend is connected.</p><div class="acts"><button class="btn ghost" onclick="sexp()">Export backup</button><button class="btn del" onclick="srst()">Reset workspace</button></div></div></section></div>`;
function ssave(){S.settings.name=$('#sn').value.trim().slice(0,20)||'Creator';S.settings.cur=$('#sc').value;save();toast('Settings saved')}
function sexp(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='vyro-backup.json';a.click();URL.revokeObjectURL(a.href)}
function srst(){if(confirm('Erase all videos, tasks, deals and events on this device?')){S=seed();save();go('home');toast('Workspace reset')}}
